##### Numpy Functions


##### 1. Write a NumPy program to compute the multiplication of two given matrixes. 
2. Write a NumPy program to compute the outer product of two given vectors. 
3. Write a NumPy program to compute the cross product of two given vectors. 
4. Write a NumPy program to compute the determinant of a given square array. 
5. Write a NumPy program to evaluate Einstein's summation convention of two given multidimensional arrays. 
6. Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension.
7. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array. 
8. Write a NumPy program to compute the Kronecker product of two given mulitdimension arrays. 
9. Write a NumPy program to compute the condition number of a given matrix. 
10. Write a NumPy program to find a matrix or vector norm. 
11. Write a NumPy program to compute the determinant of an array. 
12. Write a NumPy program to compute the inverse of a given matrix. 
13. Write a NumPy program to calculate the QR decomposition of a given matrix.
14. Write a NumPy program to compute the condition number of a given matrix. 
15. Write a NumPy program to compute the sum of the diagonal element of a given array. 


In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.matmul(a,b))


[[30 36 42]
 [66 81 96]]


In [4]:
a = np.array([1,2,3])
b= np.array([4,5,6])
print(np.outer(a,b))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [5]:
a = np.array([1,2,3])
b= np.array([4,5,6])
print(np.inner(a,b))

32


In [6]:
a = np.array([1,2,3])
b= np.array([4,5,6])
np.cross(a,b)

array([-3,  6, -3])

In [8]:
a = [[1,2],[3,4]]
print(np.linalg.det(a))

-2.0000000000000004


In [17]:
# Eigen values and eigen vectors
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.kron(a,b))

[ 4  5  6  8 10 12 12 15 18]


In [21]:
# Condition Number
a = np.array([[1,2,3],[4,5,6]])
print(np.linalg.cond(a))

12.302245504069207


In [29]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.inv(a))
a


[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
 np.trace(a)

15